### PR TITLE
feat: change favicon based on theme preference

### PR DESCRIPTION
**Pull request by raunofreiberg**
Follow-up for #53

image

image

### CODE REVIEW

**Comment by peduarte** [comment]
Nice one, thanks @raunofreiberg 

Im checking the preview link on my chrome and it looks like this 
https://modulz-website-git-fork-raunofreiberg-feat-favicon.modulz-deploys.com/

Is this expected? 

Referring back [to this comment](https://github.com/modulz/modulz-website/issues/53#issuecomment-630356261) I think we're unable to know what's the "Chrome Theme". 

In my case, I have a "black theme" for chrome, but my OS is in "light mode", therefore showing the black favicon. If I change it to light theme, then the favicon changes, so this PR is correct imo. 

But I wonder if there's any way to know the chrome theme as well?

If not, no worries.

**Comment by raunofreiberg** [comment]
Oh! I did not know that you change the theme of the browser regardless of the system theme.
 
How would you do that? Is it a custom theme that's black? [Google Chrome support has no info on this](https://support.google.com/chrome/answer/9275525?co=GENIE.Platform%3DDesktop&hl=en)

Anyway, from a bit of searching I think `prefers-color-scheme` only takes the system _mode_ into account, not the _theme_.

If that seems unfavorable, it's okay to close this 🙃

**Comment by peduarte** [comment]
Yeah that's what I thought.

Fair enough, we can't please everyone 😄 

The only thing I'd say is let's not delete the `favicon` file. It gets used in other Modulz products.

Thanks!

**Comment by raunofreiberg** [comment]
> The only thing I'd say is let's not delete the favicon file. It gets used in other Modulz products.

Restored it!

**Comment by peduarte** [comment]
Awesome! Let's take it for a spin.

Thanks! 👍

**Pull request merged**
